config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

 
  root 'tasks#index'
  
  get 'tasks' => 'tasks#index'

  get 'tasks/new' => 'tasks#new'
  post 'tasks' => 'tasks#create'
  
  get 'tasks/:id' => 'tasks#view', as: 'task'
  delete 'tasks/:id' => 'tasks#destroy'
  
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'me', to: 'me#profile', as: 'me'
  get 'login' => 'home#show', as: 'login'
  get 'google-login', to: redirect('/auth/google_oauth2')
  get 'facebook-login', to: redirect('/auth/facebook')
  
  get 'user/edit/:id', to: 'users#edit', as: 'edit_user'
  patch 'user/:id', to: 'users#update'
  
  get 'user/:id' => 'users#show', as: 'user'
  delete 'user/:id' => 'users#destroy'

  get '/learn' => 'pages#learn'
  
  get '/admin' => 'users#admin'
  
  
  
end

app/models/task.rb
class Task < ActiveRecord::Base
    #association to user db
    belongs_to :user
    
    validates_inclusion_of :category, in: Options['Categories']
    
    mount_uploader :image, ImageUploader
    
end

app/models/user.rb
class User < ActiveRecord::Base

    has_many :tasks
    
    #for identifying users based on uid 
    def self.find_or_create_from_auth_hash(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |u|
            u.provider = auth.provider 
            u.uid = auth.uid
            u.first_name = auth.info.first_name
			u.last_name = auth.info.last_name
			u.email = auth.info.email
			u.picture = auth.info.image
			u.save!
		end 
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  #methods for authentication control
  helper_method :current_user
  helper_method :authenticate
  helper_method :user_signed_in?

  def authenticate
  	redirect_to :login unless user_signed_in?
  end

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
  	# converts current_user to a boolean by negating the negation
  	!!current_user
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def show
        
    end
end

app/controllers/me_controller.rb
class MeController < ApplicationController
    before_action :authenticate 
    def profile
        if current_user.admin?
            @user = User.find(params[:id])
            @users = User.all
            @tasks_all = Task.all
        else 
            @user = current_user
            @tasks = Task.where(author: @user.username)
        end
    end
    
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def learn
    render template: "pages/_learn"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
  	@user = User.find_or_create_from_auth_hash(env["omniauth.auth"])
  	session[:user_id] = @user.id
  	if @user.username.nil?
  	  redirect_to edit_user_path(@user)
  	else
  	   redirect_to root_path
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    
    def index
        @tasks = Task.all.reverse
        @users = User.all
        @tasks.each do |t|
            if t.updated_at 
                t.show_time = t.updated_at.strftime("%d %B, %Y")
            end
        end
    end
    
    def new
        if user_signed_in?
            render 'tasks/new'
        else
            flash[:error] = "You must be logged in to submit a task"
            redirect_to '/tasks'
        end
        @task = Task.new
    end
    
    def create
        @task = Task.new(task_params)
        if @task.save
            total_points = @task.points + current_user.pointtotal
            current_user.update_attribute(:pointtotal, total_points)
            redirect_to '/tasks'
        else
            render 'new'
        end
    end
    
    def destroy
        @task = Task.find(params[:id])
        total_points = current_user.pointtotal - @task.points
        current_user.update_attribute(:pointtotal, total_points)
        @task.destroy
        redirect_to '/tasks'
    end
    
    def view
        @task = Task.find(params[:id])
    end
    
    private 
    def task_params
        params.require(:task).permit(:subject, :category, :points, :author, :user_id, :description, :image, :created_at, :updated_at)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
        @user = User.find(params[:id])
        @tasks = Task.where(author: @user.username)
        if current_user.admin?
          @users = User.all
          @tasks_all = Task.all
        end
    end
    
    def edit
      if current_user.admin?
        @user = User.find(params[:id])
      else 
        @user = current_user
      end
    end
  
    def update
      if current_user.admin?
        @user = User.find(params[:id])
      else 
        @user = current_user
      end
      begin @user.update_attributes(user_params) 
      rescue ActiveRecord::RecordNotUnique => e
        if e
          flash[:error] = "Username has already been taken"
          render 'edit_user_path'
        else 
          @user.save!
        end
      end
      flash[:success] = "Profile Updated"
      redirect_to root_path
    end
    
    def admin
      @user = current_user
      if @user.admin?
        @users = User.all
        @tasks = Task.all
      else 
        redirect_to '/tasks'
      end
    end
    
    def destroy
      @user = User.find(params[:id])
      @tasks = Task.where(author: @user.username)
      @tasks.destroy_all
      if @user == current_user
        @user.destroy
        redirect_to '/logout'
      else
        @user.destroy
        redirect_to '/tasks'
      end
      flash[:success] = "Account Deleted"
    end
    
    
    private
    def user_params
      params.require(:user).permit(:username, :pointtotal, :admin)
    end

  
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/me_helper.rb
module MeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/show.html.erb
<html>
<head>
    <title>Login/Signup Page</title>
    <%= stylesheet_link_tag "home", media: "all", "data-turbolinks-track" => "reload" %>
</head>
<body>
    <div class="jumbotron">
        <h1>Login</h1>
    </div>
    <a href="/google-login">Google Login</a>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => "reload" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!--favicon-->
  <%= favicon_link_tag asset_path('usa.png'), :rel => 'icon', :type =>  'image/png' %>


  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="tasks.scss">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
  

<%= render 'shared/header' %>

<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= yield %>


</body>
</html>

app/views/me/profile.html.erb
<html>
<head>
    <title>Profile</title>
    
    <%= stylesheet_link_tag "tasks", media: "all", "data-turbolinks-track" => "reload" %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
        
    <% if current_user %>
    
        <div class="container" id="user-title">
            <h2><%= current_user.first_name%> <%= current_user.last_name%></h2>
        </div>
        
        <div></div>
        
        <div class="container" id="user-table">
            <div class="container" id="user-one">
                <div class="container" id="user">
                    <h3> <%= current_user.username %></h3>
                </div>
                <h3 id="email"> Points: <%= current_user.email %></h3>
                <h3 id="points"> Points: <%= current_user.pointtotal %></h3>
            </div>
        </div>
        
        <div></div>
        
        <div class = "container" id="task-table">
            <div class = "container" id="user">
                <h3>My Tasks:</h3>
            </div>
            <% @tasks.each do |t| %>
                <h3 id="subject"><%= t.subject %></h3>
            <% end %>
        </div>
    <% end %>
</body>
</html>

app/views/pages/_learn.html.erb
<html>
<head>
  <title>Learn</title>
  <%= javascript_include_tag "pages", media: "all", "data-turbolinks-track" => "reload" %>
  <%= stylesheet_link_tag "pages", media: "all", "data-turbolinks-track" => "reload"%>
  <style type="text/css">
    #learn-header h1 {
    font-size: 100px;
    color: white;
}

#learn-header p {
    font-size: 30px;
    margin-bottom: 5px;
    color: white;
    font-weight: 400;
    font-variant: small-caps;
}

#learn-header {
    height: 450px;
    background-image: url("https://images.unsplash.com/photo-1534774592507-488885376ad3?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=8f04cb891ad2a6483753e937b01e6cf1&auto=format&fit=crop&w=1650&q=80");
    background-position: bottom;
    margin-bottom: 0px;
}

#learn-header .container {
    max-width: 55rem;
    margin-top: 120px;
    border: 1px solid white;
    padding-bottom: 20px;
    position: relative;
}

#learn-content {
    background-color: white;
    display: flex;
    align-content: center;
}

.card {
    margin: 18px;
}

.card h5 {
    font-size: 25px;
}
  </style>

</head>

<body>
  <div class="jumbotron text-center" id="learn-header">
    <div class="container">
      <h1>Learn</h1>
      <p>Educational Resources for Advocacy</p>
    </div>
  </div>
  
  <div class="jumbotron" id="learn-content">
  <div class="row">
  <div class="card" style="width: 25rem;">
    <a href="https://www.plannedparenthood.org/">
    <img class="card-img-top" src="https://i.imgur.com/mlqobuo.jpg" width="288px" height="180px" alt="Women's reproductive rights image">
    </a>
    <div class="card-body">
      <h5 class="card-title">Reproductive Rights</h5>
      <p class="card-text">Reproductive rights are a huge issue facing women and the country as a whole right now.</p>
      <a href="https://www.plannedparenthood.org/" class="btn btn-primary">Learn more from Planned Parenthood</a>
    </div>
  </div>
  
  
  <div class="card" style="width: 25rem;">
    <a href="https://blogs.microsoft.com/on-the-issues/2018/04/03/the-cloud-act-is-an-important-step-forward-but-now-more-steps-need-to-follow/">
    <img class="card-img-top" src="https://i.imgur.com/2pNW9nY.jpg" width="288px" height="180px" alt="Data privacy lock image">
    </a>
    <div class="card-body">
      <h5 class="card-title">Data Privacy</h5>
      <p class="card-text">On March 23, 2018, after a multi-year advocacy effort, the Clarifying Lawful Overseas Use of Data Act (the “CLOUD Act”) was signed into law as part of omnibus legislation. Passage of the CLOUD Act represents a milestone for digital privacy. U.S. privacy law now better reflects today’s cloud computing technology—not the era of the floppy disc. While the CLOUD Act advances digital privacy and provides important legal clarity, it also represents just one step in building a global data privacy framework. The U.S. must now enter into bilateral agreements with partner nations to protect privacy and strengthen law enforcement.</p>
      <a href="https://blogs.microsoft.com/on-the-issues/2018/04/03/the-cloud-act-is-an-important-step-forward-but-now-more-steps-need-to-follow/" class="btn btn-primary">Read more about the CLOUD Act</a>
    </div>
  </div>
  
  <div class="card" style="width: 25rem;">
    <a href="http://www.csecoalition.org/">
    <img class="card-img-top" src="https://i.imgur.com/F22u0ss.jpg" width="288px" height="180px" alt="Student learning computer science image">
    </a>
    <div class="card-body">
      <h5 class="card-title">Computer Science Education</h5>
      <p class="card-text">The United States leads the world in technology innovation, but our leadership is jeopardized by insufficient support for computer science education in our nation’s K-12 schools. Today, even as our economy is increasingly driven by information technology, only one of four K-12 schools in the U.S. offers any computer science courses. We can and must do better!</p>
      <a href="http://www.csecoalition.org/" class="btn btn-primary">Learn more from the Computer Science<br/>Education Coalition (CSEC)</a>
    </div>
  </div>
  
  <div class="card" style="width: 25rem;">
    <a href="http://www.bsa.org/policy/intellectual-property-and-innovation/?sc_lang=en-US">
    <img class="card-img-top" src="https://i.imgur.com/knEH6OR.jpg" width="288px" height="180px" alt="Light bulb and hand image">
    </a>
    <div class="card-body">
      <h5 class="card-title">Intellectual Property</h5>
      <p class="card-text">Intellectual property is a critical driver of technological innovation and economic competitiveness — and is at the very heart of the software business, encouraging innovators to invest in research and product development for the benefit of customers and consumers. America’s economic success and technology leadership depend on a U.S. regulatory system that supports innovation and U.S. competitiveness. Robust protections for patents, including patents for software innovations, are essential to provide incentives for the next great wave of invention. Voices for Innovation supports patent policies that promote fairness and efficiency and deter abusive practices in patent litigation.</p>
      <a href="http://www.bsa.org/policy/intellectual-property-and-innovation/?sc_lang=en-US" class="btn btn-primary">Learn more about IP protection</a>
    </div>
  </div>
  
  <div class="card" style="width: 25rem;">
    <a href="https://www.sierraclub.org/home">
    <img class="card-img-top" src="https://i.imgur.com/fF1KY3B.jpg" width="288px" height="180px" alt="Hand holding plant in soil image">
    </a>
    <div class="card-body">
      <h5 class="card-title">Environment</h5>
      <p class="card-text">Fight to protect our planet and save the environment now.</p>
      <a href="https://www.sierraclub.org/home" class="btn btn-primary">Learn more from the Sierra Club</a>
    </div>
  </div>
  </div>
  </div>
  
</body>
</html>

app/views/shared/_header.html.erb
<html>
<head>
  <title>Header</title>
  
  <style type="text/css">
    #full-navbar {
      position: -webkit-sticky; /* Safari */
      position: sticky;
      top: 0;
    }
  </style>
  <script type="text/css" src="js/materialize.min.js"></script>
  <%= stylesheet_link_tag "shared", media: "all", "data-turbolinks-track" => "reload" %>
</head>

<nav class="navbar-expand-lg navbar-dark" id="full-navbar">
  <ul class="navbar-nav" style="background-color: #01579b; width: 100%; height: 100%;">
    <img src="https://i.imgur.com/HKDm4L7.png"  width="50" height="50" alt="">
    <li class="nav-item">
      <a class="navbar-brand" style="font-size: 20px; color: white" href="/tasks">Advocacy Platform</a>
    </li>
  <li class="nav-item">
    <a class="nav-link" style="font-size: 15px; color: white" href="/learn">Learn</a>
  </li>
    <!--- <li class="nav-item"><a class="nav-link" style="font-size:15px; color:white" href="/users">Users</a></li> --->
    <% if user_signed_in? %>

      <li class="nav-item"><%= link_to('Profile', user_path(current_user), :class => 'nav-link', :style => "font-size:15px; color:white") %></li>
      <% if current_user.admin? %>
        <li class="nav-item"><a class="nav-link" style="font-size:15px; color:white" href="/admin">Admin</a></li>
      <% end %>
      <li class="nav-item"><%= link_to('Log Out', logout_path, :class => 'nav-link', :style => "text-align: center;border: none; background: transparent;font-size:15px; color:white") %></li>
    <% else %>
      <li class="nav-item"><a class="nav-link" style="font-size:15px; color: white" href="/google-login">Login with Google</a></li>
      <!--- <li class="nav-item"><a class="nav-link" style="font-size:15px; color:white" href="/users/new">Sign Up</a></li> --->
    <% end %>
  </ul>




</nav>


</html>

app/views/tasks/index.html.erb
<html>
  <head>

    <title>Tasks</title>

    <%= stylesheet_link_tag "tasks", media: "all", "data-turbolinks-track" => "reload" %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="materialize.min.css"  media="screen,projection"/>

  </head>
  <body>
    <div class="container" id="index-title">
      <% if @tasks %>
      <div class="row" id="all-tasks">
      <div class="col"></div>
      <div class="col">
        <% @tasks.each do |t| %>
            <div class="card large light-blue" style="height: 225px; width: 500px;" id="single-task">
              <div class="card-content white-text">
                <span class="card-title" style="font-size: 25px" id="user"><i><b><%= t.author %></b></i></span>
                <p id="time"><%= t.show_time %></p>
                <p id="subject" style="font-size: medium"><%= t.subject %><p/>
                <p id="category" style="font-size: medium"><%= t.category %><p/>
                <p id="points" style="font-size: medium"> Points: <%= t.points %><p/>
                <!--<p style="font-size: medium"> Image: <%= image_tag(t.image_url(:thumb).to_s) %></p>-->
                <button class = "btn waves-effect waves-light white"  id="view-task"><%= link_to('See More', task_path(t)) %></button>

             
              </div>
            </div>
        <% end %>
      <% end %>
      </div>
    <div class="col"></div>
      </div>
      </div>
    <div class="container" id="bottom-left">
      <div class="fixed-action-btn">
        <a href="/tasks/new" class="btn-floating btn-large waves-effect waves light-blue darken-4"><i class="material-icons">add</i></a>
      </div>
    </div>

      <script type="text/css" src="../../../public/materialize.min.js"></script>

  </body>
</html>

app/views/tasks/new.html.erb
<html>
    <head>
        <title>
           Submit a Report
        </title>
        
        <%= stylesheet_link_tag "tasks", media: "all", "data-turbolinks-track" => "reload" %>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="materialize.min.css"  media="screen,projection"/>
    </head>
    <body>
        .
        <div class="jumbotron" id="new-full">
            <div class="container" id="submit-title">
                <h1>Submit a Report</h1>
            </div>
            <div class="container" id="form-box">
                <%= form_for Task.new do |t| %>
                
                    <div class="container" id="form field">
                    <%= t.hidden_field :author, value: current_user.username %>
                    <%= t.hidden_field :user_id, value: current_user.id %>
                    </div>
                    
                    <div class="container" id="form field">
                    <%= t.label :subject, "Subject" %>
                    <%= t.text_field :subject %>
                    </div>
                    
                    <div class="container" id="form field">
                    <%= t.label :category, "Category" %>
                    <%= t.select :category, Options['Categories'] %>
                    </div>
                    
                    <div class="container" id="form field">
                    <%= t.label :points, "Points" %>
                    <%= t.select :points, ((1..10).map {|i| [i,i] }) %>
                    </div>
                    
                    <div class="container" id="form field">
                    <%= t.label :description, "Description" %>
                    <%= t.text_field :description %>
                    </div>
                    
                    <!--<%= t.label :image %><br>-->
                    <!--<%= t.file_field :image %>-->
                    
                    <div class="container" id="submit-button">
                    <%= t.submit "Submit Task" %>
                    </div>
                <% end %>
            </div>
        </div>
    </body>
</html>

app/views/tasks/view.html.erb
<html>
    <head>
        <title>
            New Task
        </title>
        <%= stylesheet_link_tag 'tasks' %>
    </head>
    <body>
        <h1>View Task</h1>

        <div class="container" id="index-table">
            <div class="container" id="single-task">
                <div class="container" id="user">
                    <h3> <%= @task.author %></h3>
                </div>
                <h3 id="subject"><%= @task.subject %></h3>
                <h3 id="category"><%= @task.category %></h3>
                <h3 id="points"> Points: <%= @task.points %></h3>
                <h3 id="description"><%= @task.description %></h3>
                <!--<h3> Image: <%= image_tag(@task.image_url(:thumb).to_s) %></h3>-->
                
            </div>
            <div>
                <div id="user"> </div>
                <h3><%= link_to 'View all tasks', root_path %></h3>
                <% if current_user && current_user.username == @task.author %>
                    <h3><%= link_to 'Delete', task_path(@task), method: :delete %></h3>
                <% end %>
            </div>
        </div>
        
        

    </body>
</html>

app/views/users/admin.html.erb
<html>
<head>
    <title>Admin Page</title>
    <%= stylesheet_link_tag "users", media: "all", "data-turbolinks-track" => "reload" %>
</head>
<body>
    
    <%= @users.each do |u| %>
    <div class="container" id="user-title">
        <div class="container">
            <h2><%= u.first_name%> <%= u.last_name%></h2>
            <%= image_tag(u.picture, {:style => 'width: 50px'}) %>
        </div>
    </div>
        
        
    <div class="container" id="user-table">
        <div class="container" id="user-one">
            <h3> <%= u.username %></h3>
            <h3 id="email"> Email: <%= u.email %></h3>
            <h3 id="points"> Total Points: <%= u.pointtotal %></h3>
            <%= link_to "Delete User", user_path(u), method: :delete,  data: { confirm: "Are you sure?" } %>
            <%= link_to "Edit User", edit_user_path(u) %>
        </div>
    </div>
    <% end %>
        

</body>
</html>

app/views/users/edit.html.erb
<html>
<head>
    <title>Edit</title>
    <%= stylesheet_link_tag "users", media: "all", "data-turbolinks-track" => "reload" %>
</head>
<body>
    
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<div class="jumbotron" id="edit-full">
<% if !@user.username %>
    <div class="container" id="intro-box">
    <h1>Hi, <%= @user.first_name %></h1>
    <p>To finish signing up, choose a username</p>
    <%= form_for @user do |u| %>
        <%= u.hidden_field :pointtotal, value: 0 %>
    
        <%= u.label :username %>
        <%= u.text_field :username %>
        
        <%= u.submit "Submit" %>
    <% end %>
    </div>
<% else %>
    <div class="container" id="edit-box">
    <h1><%= @user.first_name %> <%= @user.last_name%></h1>
    <%= form_for @user do |u| %>
    
        <%= u.label :username %>
        <%= u.text_field :username %>
        
        <% if current_user.admin? %>
            <%= u.label :admin %>
            <%= u.check_box :admin %>
        <% end %>
        
        <%= u.submit "Submit" %>
    <% end %>
    
    <%= link_to "Delete Account", user_path(@user), method: :delete,  data: { confirm: "Are you sure? This will also delete all assocaiated tasks." } %>
    </div>
<% end %>
</div>
</body>
</html>

app/views/users/show.html.erb
<html>
<head>
    <title>Profile</title>
    
    <%= stylesheet_link_tag "users", media: "all", "data-turbolinks-track" => "reload" %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
    
    <div class="container" id="user-title">
        <div class="container">
            <h2><%= @user.first_name%> <%= @user.last_name%></h2>
            <%= image_tag(@user.picture, {:style => 'width: 50px'}) %>
        </div>
    </div>
        
        
    <div class="container" id="user-table">
        <div class="container" id="user-one">
            <h3> <%= @user.username %></h3>
            <h3 id="email"> Email: <%= @user.email %></h3>
            <h3 id="points"> Total Points: <%= @user.pointtotal %></h3>
            <%= link_to 'Edit Profile', edit_user_path(@user) %>
        </div>
    </div>
        
    <div class = "container" id="task-table">
        <div class = "container" id="user">
        <h3>My Tasks:</h3>
        <% @tasks.each do |t| %>
            <div class="row">
                <div class="col-sm-3">
                    <h2 id="subject"><%= t.subject %></h2>
                </div>
                <div class="col-sm-3">
                    <h2>Points: <%= t.points %></h2>
                </div>
                <div class="col-sm-3">
                    <%= link_to('View', task_path(t)) %>
                </div>
            </div>
        <% end %>
        </div>
    </div>
        
        <div class="container" id="options">
            <div class="row">
                
            </div>
        </div>
</body>
</html>

app/views/users/update.html.erb
<html>
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<% render :file => 'users/edit'%>
</html>